# Generated by Django 3.2.15 on 2022-09-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='progile_img',
            new_name='profile_img',
        ),
    ]
